// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu6lnreqpDjg386a-1zw7cs2EsQLodDD4',
    appId: '1:871751942010:web:a4618833b6ab66f8b0e0c3',
    messagingSenderId: '871751942010',
    projectId: 'majung-ce508',
    authDomain: 'majung-ce508.firebaseapp.com',
    storageBucket: 'majung-ce508.firebasestorage.app',
    measurementId: 'G-58HJV1C4XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgMwWew6HG45xxx5gjXWFiWFaLQjIAVCw',
    appId: '1:871751942010:android:57a15a101f1f47f3b0e0c3',
    messagingSenderId: '871751942010',
    projectId: 'majung-ce508',
    storageBucket: 'majung-ce508.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1V1tsO2uVdQYXK3kcfxPZDjDowg3bChs',
    appId: '1:871751942010:ios:f5bbfc4fc45e59fbb0e0c3',
    messagingSenderId: '871751942010',
    projectId: 'majung-ce508',
    storageBucket: 'majung-ce508.firebasestorage.app',
    iosBundleId: 'com.example.majung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1V1tsO2uVdQYXK3kcfxPZDjDowg3bChs',
    appId: '1:871751942010:ios:f5bbfc4fc45e59fbb0e0c3',
    messagingSenderId: '871751942010',
    projectId: 'majung-ce508',
    storageBucket: 'majung-ce508.firebasestorage.app',
    iosBundleId: 'com.example.majung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu6lnreqpDjg386a-1zw7cs2EsQLodDD4',
    appId: '1:871751942010:web:f0fea4f5c976bf33b0e0c3',
    messagingSenderId: '871751942010',
    projectId: 'majung-ce508',
    authDomain: 'majung-ce508.firebaseapp.com',
    storageBucket: 'majung-ce508.firebasestorage.app',
    measurementId: 'G-7TR95ZB3FW',
  );
}
